
name: Deploy to slintpad.com

on:
  push:
    paths: 'slintpad/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: npm install
        run: |
          cd slintpad && npm install

      - name: Clone website directory
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          ssh-agent sh -c 'echo "${{ secrets.WEBSITE_READ_SSH_KEY }}" | ssh-add - && git clone git@github.com:slint-ui/website.git  --depth 1'

      - name: Copy index.html and 404.html
        run: |
          cp website/docs.html index.html
          cp website/404.html 404.html
          rm -rf website

      - name: Set environment variables
        run: |
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Publish to staging-slint from staging-dist
        run: |
            npx wrangler@3 pages deploy . --project-name=slintpad  --commit-dirty=true
