
name: Deploy to slintpad.com

on:
  push:
    paths: 'slintpad/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./slintpad
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: npm install
        run: |
          npm install

      - name: Clone website directory
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          ssh-agent sh -c 'echo "${{ secrets.WEBSITE_READ_SSH_KEY }}" | ssh-add - && git clone -b prod --single-branch git@github.com:slint-ui/website.git  --depth 1'

      - name: Generate 404.html
        run: |
          mkdir -p website/output
          cd website && go run generator/generator.go -skip-agreements
  
      - name: Copy 404.html
        run: |
          cp website/output/404.html 404.html
          rm -rf website

      - name: Set environment variables
        run: |
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Publish to slintpad
        run: |
            npx wrangler@3 pages deploy . --project-name=slintpad  --commit-dirty=true
