
name: Deploy to snapshots.slint.dev

on:
  push:
    paths: 'snapshots/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snapshots
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: npm install
        run: |
          npm install

      - name: Clone website directory
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          ssh-agent sh -c 'echo "${{ secrets.WEBSITE_READ_SSH_KEY }}" | ssh-add - && git clone -b prod --single-branch git@github.com:slint-ui/website.git  --depth 1'

      - name: Generate docs.html and 404.html
        run: |
          mkdir -p website/output
          cd website && go run generator/generator.go -skip-agreements
  
      - name: Copy docs.html and 404.html
        run: |
          cp website/output/docs.html index.html
          cp website/output/404.html 404.html
          rm -rf website

      - name: Install Netlify
        run: |
          npm install netlify-cli --save-dev

      - name: Install Dependencies
        run: |
          npm ci

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir . \
            --site ${{ secrets.NETLIFY_SNAPSHOTS_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
