
name: Test updation of versions.json

on:
  workflow_dispatch:
    inputs:
        version:
            type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            releases/versions.json

      - name: Print contents before update
        run: cat releases/versions.json

      - name: Update version in versions.json
        run: |
            sed -i '0,/"version": "[0-9]\+\.[0-9]\+\.[0-9]\+"/s//"version": "${{ inputs.version }}"/' releases/versions.json

      - name: Print contents before update
        run: cat releases/versions.json
