
name: Scrape a release with typesense

on:
  workflow_dispatch:

jobs:
  scrape:
    services:
        site:
            image: nginx
            volumes:
                - ${{ github.workspace }}/:/usr/share/nginx/html:ro
            ports:
                - 80:80
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: test
        run: |
            curl http://localhost:80 > test.html
            cat test.html