
name: Scrape a release with typesense

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: tj-actions/docker-run@v2
        id: docker-run
        with:
          name: nginx
          image: nginx:latest
          options: "-d -p 80:80"
      - name: Populate web server
        run: docker cp snapshots/master/docs/slint nginx:/usr/share/nginx/html
      - name: test
        run: |
            curl http://localhost:80 > test.html
            cat test.html