
name: Scrape a release with typesense

on:
  workflow_dispatch:

jobs:
  scrape:
    services:
        site:
            image: nginx
#            volumes:
#                - ${{ github.workspace }}/snapshots/master/docs/slint/:/usr/share/nginx/html:ro
            ports:
                - 80:80
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
            path: snapshots
      - name: Populate web server
        run: docker cp snapshots site:/usr/share/ngnix/html
      - name: test
        run: |
            curl http://localhost:80 > test.html
            cat test.html